baseurl: /
relativeurls: yes
publishDir: docs
title: EMCR Brain Science Network Website
theme: hugo-calade
permalinks:
  post: /post/:slug/
  project: /project/:slug/
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Strategic Plan
      url: /strategicplan/
      weight: 2
    - name: Profiles
      url: /profiles/
      weight: 3
    - name: Steering Committee
      url: /steeringcommittee/
      weight: 4
    - name: Events
      url: /events/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 6
    - name: Twitter feed
      url: /twitter-feed/
      weight: 7
    - name: EMCR groups
      url: /emcr-groups/
      weight: 8

params:
  colorAccent1: '#ff69b4'
  colorAccent2: '#ba68c8'
  colorFade: '#888888'
  colorPage: '#333333'
  colorText: '#dddddd'
  description: This is the new website for the Australasian EMCR Brain Sciences network 
  footer: EMCRs are early-mid-career researchers in ANY area doing brain-related things
  siteHeader: header/EMCRNetworkLogo.png
  siteProfile: 
  twitterImage: header/EMCR-BSN-logo.png
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      disqusShortname: ''
      footnotereturnlinkcontents: ↩
      googleAnalytics: ''
      ignoreFiles:
        - \.Rmd$
        - \.Rmarkdown$
        - _files$
        - _cache$
      languageCode: en-us
      preserveTaxonomyNames: yes
      unsafe: yes
